data:
    name: 'miniimagenet'
    im_size: 84
    augment: 1
    augment_val: 0
    augment_test: 2
model:
    structure: 'resnet10'
    num_classes: 64
io:
    exp_name: 'default'
ctrl:
    gpu_id: 2
    ep_save: 500
    ep_vis_loss: 100
    ep_val: 500
train:
    nep: 3
    lr: 0.001
    weight_decay: 0.0
    lr_scheduler: [1, 2]
    lr_gamma: 0.1
    clip_grad: True
    mode: 'openfew'
    open_detect: 'gauss'
    entropy: True
    aux: True
    loss_scale_entropy_lut: [[30000], [0.5]]
    loss_scale_aux_lut: [[5000, 10000, 20000, 30000], [0.5, 0.3, 0.1, 0.0]]
fsl:
    n_way: 5
    n_way_val: 5
    n_way_test: 5
    k_shot: 1
    k_shot_val: 1
    k_shot_test: 1
    m_query: 15
    m_query_val: 15
    m_query_test: 15
    p_base: 75
    iterations: 10000
    iterations_val: 100
    iterations_test: 600
open:
    n_cls: 5
    n_cls_val: 5
    n_cls_test: 5
    m_sample: 15
    m_sample_val: 15
    m_sample_test: 15
